fmfn_encarta/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render_to_response, RequestContext
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView
from grappelli import urls as grapelli_urls
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin
from apps.fmfn import views

from django.http import HttpResponse

redirect = RedirectView.as_view

urlpatterns = [

	# Search interface
	url(r'^', include([

		url(r'^$', redirect(url = reverse_lazy('search')), name = 'index'),  # GET
		url(r'^search/', include([

			url(r'^$', views.search.search, name = 'search'),  # GET
	 		url(r'^api/$', views.search.search, name = 'filter')  # POST

		]))

	])),

	# Content management
	 url(r'^content/', include([

	 	url(r'create/$', views.materials.create, name = 'create'),  # GET, PUT
	 	url(r'^(?P<content_id>[\d]+)/', include([

	 		url(r'^$',views.materials.view, name = 'view'),  # GET, POST
	 		url(r'^edit/$', views.materials.edit, name = 'edit'),  # GET, POST, DELETE
		    url(r'^download/$', views.materials.download, name = 'download'),  # GET

	 	]))

	 ], namespace = 'content', app_name = 'apps.fmfn')),

	# Tags
	url(r'^tags/(?P<tag_type>type|theme|language)/', include([

        url(r'^$', views.tags.tags, name = 'list'),  # GET
        url(r'^create/$', views.tags.tags, name = 'create', kwargs = { 'action': 'create' }),  # POST
        url(r'^(?P<tag_id>[\d]+)/edit/$', views.tags.tags, name = 'edit', kwargs = { 'action': 'edit' }), # POST
		url(r'^(?P<tag_id>[\d]+)/delete/$', views.tags.tags, name = 'delete', kwargs = { 'action': 'delete' })  # POST

    ], namespace = 'tags', app_name = 'fmfn')),

	# Account management
	url(r'^accounts/', include([

		url(r'^login/$', views.accounts.login, name = 'login'),  # GET, POST
		url(r'^logout/$', views.accounts.logout, name = 'logout'),  # GET
		url(r'^recover/', include([

			url(r'^$', views.accounts.recover, name = 'recover', kwargs = { 'stage': 'recover' }),  # GET, POST
			url(r'^reset/(?P<user_id>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.accounts.recover, name = 'reset', kwargs = { 'stage': 'reset' })  # GET, POST

		]))

	], namespace = 'accounts', app_name = 'apps.fmfn')),
	
	# User management
	url(r'^users/', include([

	 	url(r'^$', views.users.search, name = 'list'),  # GET
	 	url(r'^api/$', views.users.search, name = 'filter'),  # POST
		url(r'^create/$', views.users.create, name = 'create'),  # GET, POST
	 	url(r'^(?P<user_id>[\d]+)/', include([

	 		url(r'^$',  views.users.view, name = 'view'),  # GET, POST
	 		url(r'^edit/$', views.users.edit, name = 'edit')  # GET, POST, DELETE

		]))

	], namespace = 'users', app_name = 'apps.fmfn')),

	# Portfolio (favorites) management
	url(r'^portfolio/', include([

		url(r'^$', views.portfolio.manage, name = 'view'),  # GET
		url(r'^(?P<content_id>[\d]+)/$', views.portfolio.manage, name = 'edit')  # PUT, DELETE

	], namespace = 'portfolio', app_name = 'fmfn')),

	# Management
	url(r'^manage/', include([

		url(r'^statistics/', include([

			url(r'^$', views.reporting.select, name = 'reporting'),  # GET
			url(r'^content/$', views.reporting.materials, name = 'content'),  # GET
			url(r'^users/$', views.reporting.users, name = 'users'),  # GET
			url(r'^comments/$', views.reporting.comments, name = 'comments')  # GET

		])),
		url(r'^reports/', include([

			url(r'^$', views.reports.reports, name = 'list'),  # GET
			url(r'^create/(?P<content_id>[\d]+)/$', views.reports.reports, name = 'create'),  # POST
			url(r'^(?P<report_id>[\d]+)/$', views.reports.reports, name = 'manage')  # PATCH, DELETE

		]))

	], namespace = 'management', app_name = 'apps.fmfn')),

	# Added here as they seem to require their own namespace
	url(r'^manage/advanced/', include(admin.site.urls)),
	url(r'^manage/grappelli/', include(grapelli_urls))

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

apps/fmfn/forms/comments.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.translation import ugettext_lazy as _
from django_select2.forms import Select2MultipleWidget
from apps.fmfn.models import Comment
from django.forms import *
from django.forms import ModelForm as Form

__all__ = [ 'CommentForm' ]

class CommentForm(Form):

	class Meta(object):

		model = Comment
		fields = [ 'content', 'rating_value', 'user', 'material' ]
		widgets = {
			'user': HiddenInput(),
			'material': HiddenInput(),
			'content': Textarea(attrs = { 'placeholder': _('Write a comment here'), 'rows': 6, 'style': 'resize: none;' }),
			'rating_value': RadioSelect()
		}

apps/fmfn/forms/languages.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth import get_user_model
from apps.fmfn.models import Language
from django.forms import *
from django.forms import ModelForm as Form

__all__ = [ 'UserForm' ]
User = get_user_model()

class UserForm(Form):

	class Meta(object):

		model = Language
		fields = [
			'name'
		]
		widgets = {
			'name': TextInput(attrs = { 'placeholder': _('Tag name') }),
		}

apps/fmfn/forms/materials.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.translation import ugettext_lazy as _
from django_select2.forms import Select2MultipleWidget
from apps.fmfn.models import Material
from django.forms import *
from django.forms import ModelForm as Form

__all__ = [ 'MaterialForm' ]

class MaterialForm(Form):

	def clean(self):

		cleaned_data = Form.clean(self)

		content = cleaned_data.get('content')
		link = cleaned_data.get('link')

		if content and link: raise ValidationError({ 'content': _('El material debe tener al menos un link o documento, pero no ambos') })
		if not content and not link: raise ValidationError({ 'content': _('El material debe tener al menos un link o documento, pero no ambos') })

	class Meta(object):

		model = Material
		fields = [
			'title',
			'description',
			'content',
			'link',
			'suggested_ages',
			'types',
			'themes',
			'languages',
			'user'
		]
		widgets = {
			'title': TextInput(attrs = { 'placeholder': _('Título del material') }),
			'description': Textarea(attrs = { 'placeholder': _('Breve descripción del material'), 'rows': 6, 'style': 'resize: none;' }),
			'content': ClearableFileInput(attrs = { 'placeholder': _('Documentation') }),
			'link': URLInput(attrs = { 'placeholder': _('Link a referencia en formato http') }),
			'suggested_ages': CheckboxSelectMultiple(),
			'types': CheckboxSelectMultiple(),
			'themes': Select2MultipleWidget(),
			'languages': CheckboxSelectMultiple(),
			'user': HiddenInput()
		}

apps/fmfn/forms/themes.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth import get_user_model
from apps.fmfn.models import Theme
from django.forms import *
from django.forms import ModelForm as Form

__all__ = [ 'UserForm' ]
User = get_user_model()

class UserForm(Form):

	class Meta(object):

		model = Theme
		fields = [
			'name'
		]
		widgets = {
			'name': TextInput(attrs = { 'placeholder': _('Tag name') }),
		}

apps/fmfn/views/accounts.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth import (
	login as login_to_site,
	logout as logout_from_site,
	update_session_auth_hash as update_session
)
from django.shortcuts import render_to_response, redirect, RequestContext
from django.contrib.auth.tokens import default_token_generator as tokens
from django.utils.http import urlsafe_base64_decode as base64_decode
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import update_last_login
from django.views.decorators.csrf import csrf_protect
from django.utils.decorators import method_decorator
from apps.fmfn.forms import LoginForm, RecoveryForm
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth import get_user_model
from django.http import HttpResponseForbidden
from django.utils.http import force_text
from apps.fmfn.models import ActionLog
from django.views.generic import View

__all__ = [
	'login',
	'logout',
	'recover'
]
User = get_user_model()

class LoginView(View):
	""" This view handles user session creation. When a user is sent to this view, the user is prompted to provide login
		credentials. These credentials are validated and matched to a user account, hence authenticating him/her. When
		the user is authenticated, the user is logged in to the site and redirected to the last page he/she visited or
		the home page if no page was previously visited.
	"""

	def get(self, request):

		# Get redirect URL
		redirect_url = request.REQUEST.get('next', reverse_lazy('index'))

		# Check if user has been authenticated before - if so, redirect him/her to the main site
		if request.user is not None and request.user.is_authenticated():

			ActionLog.objects.log_account('User redirected since already logged in', user = request.user, status = 302)
			return redirect(redirect_url)

		# Create the login form and render the template
		form = LoginForm()
		return render_to_response('accounts/login.html', context = RequestContext(request, locals()))
	@method_decorator(csrf_protect)
	def post(self, request):

		# Get redirect URL
		redirect_url = request.REQUEST.get('next', reverse_lazy('index'))

		# Check if user has been authenticated before - if so, redirect him/her to the main site
		if request.user is not None and request.user.is_authenticated():

			ActionLog.objects.log_account('User redirected since already logged in', user = request.user, status = 302)
			return redirect(redirect_url)

		form = LoginForm(request.POST)
		if form.is_valid():

			# Login the authenticated user to the site and redirect - remember to log this event
			user = form.user
			ActionLog.objects.log_account('User logged in to site (current permissions: %s)' % user.groups, user = user, status = 200)
			login_to_site(request, user)
			update_last_login(None, user = user)

			return redirect(redirect_url)

		# Login failed - report errors back to the user
		ActionLog.objects.log_account('Failed attempt to log in to site (requested account: %s)' % form.cleaned_data['email_address'], status = 401)

		return render_to_response('accounts/login.html',
			context = RequestContext(request, locals()),
			status = 401
		)

login = LoginView.as_view()

class LogoutView(View):
	""" View that handles the user session invalidation logic. When a user is pointed to this view, the session is logged,
		invalidated and the user is redirected to the login page to sign up again (this is the default behavior).
	"""

	@method_decorator(login_required)
	def get(self, request):

		# User is logging out - log this event
		user = request.user
		ActionLog.objects.log_account('User logged out from site', user = user)

		# Proceed to log out the user
		logout_from_site(request)
		return redirect(reverse_lazy('accounts:login'))

logout = LogoutView.as_view()

class RecoverView(View):
	""" View that handles user account recovery. Recovery is carried on in two phases, each using two steps. These phases
		are "recovery" and "reset". In "recovery" phase, the account is located by means of user input and an email address
		is sent to the account to retake the process in a later time. The "reset" phase allows the user to change the
		account's password. The email sent by recovery has an expiry date of a week since the emission date and is a one-time
		only token to change the password: once used, the link is invalidated.

		This view allows changing the password of a logged-out user only. If the user was already logged in, the attempt
		is blocked since this could imply an attack. Also, the generated token is protected against tampering to prevent
		faking the request and hijacking user sessions. Once a password is changed, all active sessions (if any) are invalidated
		and the user is redirected to login.
	"""

	def get(self, request, user_id = '', token = '', stage = ''):

		# Check if user has been authenticated before - if so, redirect him/her to the main site
		if request.user is not None and request.user.is_authenticated():

			ActionLog.objects.log_account('User redirected since already logged in', user = request.user, status = 302)
			return redirect(reverse_lazy('index'))

		# This view is based on recovery stage. There are two stages: "recover" and "reset".
			# In "recover", the user account is identified and a next steps mail is sent to the user's email address
			# In "reset", the user is prompted to set a new password
		# The GET method processes both stages' form rendering. Care is taken to make this as legible as possible, and
		# as commented as possible
		if stage == 'recover':

			# We are in "recover" stage: we must ask the user for the account he/she wishes to recover
			# Add the recovery form, in "recover" mode, and render the stuff
			form = RecoveryForm(stage = stage)
			return render_to_response('accounts/recover.html', context = RequestContext(request, locals()))

		elif stage == 'reset':

			# We are in "reset" stage: we must validate the token and, if valid, prompt the user to reset his/her password
			# Identify the user - if the user is invalid, we may have an in-progress security breach
			try: user = User.objects.get(id = int(force_text(base64_decode(user_id))))
			except User.DoesNotExist: user = None

			if user is None or not tokens.check_token(user, token):

				# The URL has been tampered with - abort right now
				ActionLog.objects.log_account('URL tampering attempt detected: aborting recovery process', status = 403, user = user)
				return HttpResponseForbidden()

			form = RecoveryForm(stage = stage, user = user)
			return render_to_response('accounts/reset.html', context = RequestContext(request, locals()))

		return HttpResponseForbidden()
	@method_decorator(csrf_protect)
	def post(self, request, user_id = '', token = '', stage = ''):

		# Check if user has been authenticated before - if so, redirect him/her to the main site
		if request.user is not None and request.user.is_authenticated():

			ActionLog.objects.log_account('User redirected since already logged in', user = request.user, status = 302)
			return redirect(reverse_lazy('index'))

		if stage == 'recover':

			# Create the form in "recover" mode and attempt to validate it
			form = RecoveryForm(request.POST, stage = stage)
			if form.is_valid():

				# The form was submitted correctly, thus we send the email and notify the user on further steps
				user = form.user
				ActionLog.objects.log_account('Initiated account recovery for user (current permissions: %s)' % user.groups, user = user, status = 200)
				form.send_recovery_email(request, user, tokens.make_token(user))

				return render_to_response('accounts/recovering.html', context = RequestContext(request, locals()))

			# The account is invalid: notify this error to the user and log it
			email = form.cleaned_data['email_address']
			ActionLog.objects.log_account('Attempted to recover password of invalid account (email address: %s)' % email, status = 401)

			return render_to_response('accounts/recover.html',
				context = RequestContext(request, locals()),
				status = 401
			)
		elif stage == 'reset':

			# Identify the user - if the user is invalid, we may have an in-progress security breach
			try: user = User.objects.get(id = int(force_text(base64_decode(user_id))))
			except User.DoesNotExist: user = None

			if user is None or not tokens.check_token(user, token):

				# The URL has been tampered with - abort right now
				ActionLog.objects.log_account('URL tampering attempt detected: aborting recovery process', status = 403, user = user)
				return HttpResponseForbidden()

			# Validate the user data using the form in "complete" mode
			form = RecoveryForm(request.POST, stage = stage, user = user)
			if form.is_valid():

				# Reset the user password
				ActionLog.objects.log_account('Resetting password for user account', status = 200, user = user)
				password = form.cleaned_data['password']
				user.set_password(password)
				user.save()

				# Invalidate all sessions since they are no longer valid
				update_session(request, user)
				return redirect(reverse_lazy('accounts:login'), context = RequestContext(request, locals()))

			# The form could not be validated due to incompatible passwords
			ActionLog.objects.log_account('Attempted to change password for user', status = 401, user = user)
			return render_to_response('accounts/reset.html',
				context = RequestContext(request, locals()),
				status = 401
			)

		return HttpResponseForbidden()

recover = RecoverView.as_view()

apps/fmfn/views/createMaterial.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import redirect, render_to_response, RequestContext
from django.contrib.auth import login as login_to_site
from django.views.decorators.csrf import csrf_protect
from django.utils.decorators import method_decorator
from django.core.urlresolvers import reverse_lazy
from django.views.generic import View
from apps.fmfn.forms import materials

__all__ = [ 'createMaterial' ]


class CreateMaterialView(View):

	def post(self,request):

		# Validate the form
		form = materials(request.POST)
		if form.is_valid():

			# Log in the user into the system
			title = form.title
			description = form.description

			# Redirect the user to the main site
			return redirect(reverse_lazy('home'))

		return render_to_response('accounts/login.html', context = RequestContext(request, locals()), status = 401)
login = CreateMaterialView.as_view()

apps/fmfn/templates/base/base-2cols.html
{% extends "base/base.html" %}
{% load static i18n widget_tweaks %}
{% load roles %}

{% block content %}
    <div id="header">Modelo NWL</div>
    <div id="navigation">
        {% if user|has_role:'parent' %}<a href="{% url 'search' %}">
            <div class="navigation-item {% block busqueda-active %}{% endblock busqueda-active %}"><i
                    class="fa fa-search"></i>{% trans 'Busqueda' %}</div>
        </a>{% endif %}
        {% if user|has_role:'teacher' %}
            <a href="{% url 'portfolio:view' %}">
                <div class="navigation-item {% block favoritos-active %}{% endblock favoritos-active %}"><i
                        class="fa fa-star"></i>{% trans 'Mis favoritos' %}</div>
            </a>
        {% endif %}
        {% if user|has_role:'user manager' and user.role.name != 'content manager' %}
            <a href="{% url 'users:list' %}">
                <div class="navigation-item {% block usuarios-active %}{% endblock usuarios-active %}"><i
                        class="fa fa-users"></i>{% trans 'Usuarios' %}</div>
            </a>
        {% endif %}
        {% if user|has_role:'content manager' %}
            <a href="{% url 'management:list' %}">
                <div class="navigation-item {% block errores-active %}{% endblock errores-active %}"><i
                        class="fa fa-exclamation-triangle"></i>{% trans 'Reportes de error' %}</div>
            </a>
        {% endif %}
        {% if user|has_role:'administrator' %}
            <a href="{% url 'management:reporting' %}">
                <div class="navigation-item {% block estadisticas-active %}{% endblock estadisticas-active %}"><i
                        class="fa fa-list-ol"></i>{% trans 'Estadísticas' %}</div>
            </a>
        {% endif %}
        {% if user|has_role:'teacher' %}
            <a href="{% url 'users:view' user.id %}">
                <div class="navigation-item {% block cuenta-active %}{% endblock cuenta-active %}"><i
                        class="fa fa-user"></i>{% trans 'Mi cuenta' %}</div>
            </a>
        {% endif %}
        {% if user|has_role:'content manager' %}
            <a href="{% url 'content:create' %}">
                <div class="navigation-item {% block subir-active %}{% endblock subir-active %}"><i
                        class="fa fa-upload"></i>{% trans 'Subir material' %}</div>
            </a>
        {% endif %}
        <a href="{% url 'accounts:logout' %}" class="logout-link">
            <div class="navigation-item last"><i class="fa fa-sign-out"></i>{% trans 'Salir' %}</div>
        </a>
        <!--data-reveal-id="myModal"-->
    </div>
    <div id="canvas">
        {% block canvas %} Pon aqui tu contenido {% endblock %}
    </div>
    {% block modals %}
        <div id="myModal" class="reveal-modal" data-reveal aria-labelledby="modalTitle" aria-hidden="true"
             role="dialog">
            <h2 id="modalTitle">Awesome. I have it.</h2>

            <p class="lead">Your couch. It is mine.</p>

            <p>I'm a cool paragraph that lives inside of an even cooler modal. Wins!</p>
            <a class="close-reveal-modal" aria-label="Close">&#215;</a>
        </div>
    {% endblock %}
{% endblock content %}

apps/fmfn/templates/base/base.html
{% load static i18n widget_tweaks %}
{% get_current_language as language %}

<!DOCTYPE html>
<html lang="{{ language }}" xmlns="http://www.w3.org/1999/html">
<head>
    <title>{% block title %}{% endblock %}</title>

    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta http-equiv="Content-Language" content="es"/>

    <!-- CSS -->
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700' rel='stylesheet' type='text/css'/>
    <link href="" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/main.css' %}" rel="stylesheet"/>
    {% block css %}{% endblock %}

    <!-- JS -->
    <script type="text/javascript" src="{% static 'js/foundation/vendor/modernizr.js' %}"></script>
    {% block js_head %}{% endblock %}

</head>
<body>
{% block content %}{% endblock %}

<div class="modals">
    {% block modals %}{% endblock %}
</div>

<!-- JS -->
<script src="{% static 'js/foundation/vendor/jquery.js' %}"></script>
<script src="{% static 'js/foundation/vendor/fastclick.js' %}"></script>
<script type="text/javascript" src="{% static 'js/foundation/foundation.js' %}"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.9/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.9/js/dataTables.foundation.min.js"></script>
<link href="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/css/select2.min.css" rel="stylesheet"/>
<script src="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/js/select2.min.js"></script>
<script>
    $(document).foundation({
        reveal: {
            multiple_opened: true,
            close_on_background_click: false,
            close_on_esc: false
        }
    });
    $(document).ready(function () {
        $('.reveal-modal').css('max-height', $('html').height() - 110 + 'px'); // 100 +10px to keep modal effect visible


    });
    // Reset max-height after window resize
    $(window).resize(function () {
        $('.reveal-modal').css('max-height', $('html').height() - 110 + 'px');
    });
    $('select').select2();
    $("form").submit(function (e) {

        var ref = $(this).find("[required]");

        $(ref).each(function () {
            if ($(this).val() == '') {
                alert("Llena todos los campos requeridos");
                $(this).parent().removeClass("error-safari").addClass("error-safari");
                $(this).focus();
                e.preventDefault();
                return false;
            }
            else {
                $(this).parent().removeClass("error-safari");
            }
        });
        return true;
    });
    {% block js-inline %}{% endblock %}
</script>
{% block js_footer %}{% endblock %}
</body>
</html>