fmfn_encarta/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render_to_response, RequestContext
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView
from grappelli import urls as grapelli_urls
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin
from apps.fmfn import views

from django.http import HttpResponse

redirect = RedirectView.as_view

urlpatterns = [

	# Search interface
	url(r'^', include([

		url(r'^$', redirect(url = reverse_lazy('search')), name = 'index'),  # GET
		url(r'^search/', include([

			url(r'^$', views.search.search, name = 'search'),  # GET
	 		url(r'^api/$', views.search.search, name = 'filter')  # POST

		]))

	])),

	# Content management
	 url(r'^content/', include([

	 	url(r'create/$', views.materials.create, name = 'create'),  # GET, PUT
	 	url(r'^(?P<content_id>[\d]+)/', include([

	 		url(r'^$',views.materials.view, name = 'view'),  # GET, POST
	 		url(r'^edit/$', views.materials.edit, name = 'edit'),  # GET, POST, DELETE
		    url(r'^download/$', views.materials.download, name = 'download'),  # GET

	 	]))

	 ], namespace = 'content', app_name = 'apps.fmfn')),

	# Tags
	url(r'^tags/(?P<tag_type>type|theme|language)/', include([

        url(r'^$', views.tags.tags, name = 'list'),  # GET
        url(r'^create/$', views.tags.tags, name = 'create', kwargs = { 'action': 'create' }),  # POST
        url(r'^(?P<tag_id>[\d]+)/edit/$', views.tags.tags, name = 'edit', kwargs = { 'action': 'edit' }), # POST
		url(r'^(?P<tag_id>[\d]+)/delete/$', views.tags.tags, name = 'delete', kwargs = { 'action': 'delete' })  # POST

    ], namespace = 'tags', app_name = 'fmfn')),

	# Account management
	url(r'^accounts/', include([

		url(r'^login/$', views.accounts.login, name = 'login'),  # GET, POST
		url(r'^logout/$', views.accounts.logout, name = 'logout'),  # GET
		url(r'^recover/', include([

			url(r'^$', views.accounts.recover, name = 'recover', kwargs = { 'stage': 'recover' }),  # GET, POST
			url(r'^reset/(?P<user_id>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.accounts.recover, name = 'reset', kwargs = { 'stage': 'reset' })  # GET, POST

		]))

	], namespace = 'accounts', app_name = 'apps.fmfn')),
	
	# User management
	url(r'^users/', include([

	 	url(r'^$', views.users.search, name = 'list'),  # GET
	 	url(r'^api/$', views.users.search, name = 'filter'),  # POST
		url(r'^create/$', views.users.create, name = 'create'),  # GET, POST
	 	url(r'^(?P<user_id>[\d]+)/', include([

	 		url(r'^$',  views.users.view, name = 'view'),  # GET, POST
	 		url(r'^edit/$', views.users.edit, name = 'edit')  # GET, POST, DELETE

		]))

	], namespace = 'users', app_name = 'apps.fmfn')),

	# Portfolio (favorites) management
	url(r'^portfolio/', include([

		url(r'^$', views.portfolio.manage, name = 'view'),  # GET
		url(r'^(?P<content_id>[\d]+)/$', views.portfolio.manage, name = 'edit')  # PUT, DELETE

	], namespace = 'portfolio', app_name = 'fmfn')),

	# Management
	url(r'^manage/', include([

		url(r'^statistics/', include([

			url(r'^$', views.reporting.select, name = 'reporting'),  # GET
			url(r'^content/$', views.reporting.materials, name = 'content'),  # GET
			url(r'^users/$', views.reporting.users, name = 'users'),  # GET
			url(r'^comments/$', views.reporting.comments, name = 'comments')  # GET

		])),
		url(r'^reports/', include([

			url(r'^$', views.reports.reports, name = 'list'),  # GET
			url(r'^create/(?P<content_id>[\d]+)/$', views.reports.reports, name = 'create'),  # POST
			url(r'^(?P<report_id>[\d]+)/$', views.reports.reports, name = 'manage')  # PATCH, DELETE

		]))

	], namespace = 'management', app_name = 'apps.fmfn')),

	# Added here as they seem to require their own namespace
	url(r'^manage/advanced/', include(admin.site.urls)),
	url(r'^manage/grappelli/', include(grapelli_urls))

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

apps/fmfn/forms/comments.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.translation import ugettext_lazy as _
from django_select2.forms import Select2MultipleWidget
from apps.fmfn.models import Comment
from django.forms import *
from django.forms import ModelForm as Form

__all__ = [ 'CommentForm' ]

class CommentForm(Form):

	class Meta(object):

		model = Comment
		fields = [ 'content', 'rating_value', 'user', 'material' ]
		widgets = {
			'user': HiddenInput(),
			'material': HiddenInput(),
			'content': Textarea(attrs = { 'placeholder': _('Write a comment here'), 'rows': 6, 'style': 'resize: none;' }),
			'rating_value': RadioSelect()
		}

apps/fmfn/forms/languages.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth import get_user_model
from apps.fmfn.models import Language
from django.forms import *
from django.forms import ModelForm as Form

__all__ = [ 'UserForm' ]
User = get_user_model()

class UserForm(Form):

	class Meta(object):

		model = Language
		fields = [
			'name'
		]
		widgets = {
			'name': TextInput(attrs = { 'placeholder': _('Tag name') }),
		}

apps/fmfn/forms/materials.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.translation import ugettext_lazy as _
from django_select2.forms import Select2MultipleWidget
from apps.fmfn.models import Material
from django.forms import *
from django.forms import ModelForm as Form

__all__ = [ 'MaterialForm' ]

class MaterialForm(Form):

	def clean(self):

		cleaned_data = Form.clean(self)

		content = cleaned_data.get('content')
		link = cleaned_data.get('link')

		if content and link: raise ValidationError({ 'content': _('El material debe tener al menos un link o documento, pero no ambos') })
		if not content and not link: raise ValidationError({ 'content': _('El material debe tener al menos un link o documento, pero no ambos') })

	class Meta(object):

		model = Material
		fields = [
			'title',
			'description',
			'content',
			'link',
			'suggested_ages',
			'types',
			'themes',
			'languages',
			'user'
		]
		widgets = {
			'title': TextInput(attrs = { 'placeholder': _('Título del material') }),
			'description': Textarea(attrs = { 'placeholder': _('Breve descripción del material'), 'rows': 6, 'style': 'resize: none;' }),
			'content': ClearableFileInput(attrs = { 'placeholder': _('Documentation') }),
			'link': URLInput(attrs = { 'placeholder': _('Link a referencia en formato http') }),
			'suggested_ages': CheckboxSelectMultiple(),
			'types': CheckboxSelectMultiple(),
			'themes': Select2MultipleWidget(),
			'languages': CheckboxSelectMultiple(),
			'user': HiddenInput()
		}

apps/fmfn/forms/themes.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth import get_user_model
from apps.fmfn.models import Theme
from django.forms import *
from django.forms import ModelForm as Form

__all__ = [ 'UserForm' ]
User = get_user_model()

class UserForm(Form):

	class Meta(object):

		model = Theme
		fields = [
			'name'
		]
		widgets = {
			'name': TextInput(attrs = { 'placeholder': _('Tag name') }),
		}

apps/fmfn/views/accounts.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth import (
	login as login_to_site,
	logout as logout_from_site,
	update_session_auth_hash as update_session
)
from django.shortcuts import render_to_response, redirect, RequestContext
from django.contrib.auth.tokens import default_token_generator as tokens
from django.utils.http import urlsafe_base64_decode as base64_decode
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import update_last_login
from django.views.decorators.csrf import csrf_protect
from django.utils.decorators import method_decorator
from apps.fmfn.forms import LoginForm, RecoveryForm
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth import get_user_model
from django.http import HttpResponseForbidden
from django.utils.http import force_text
from apps.fmfn.models import ActionLog
from django.views.generic import View

__all__ = [
	'login',
	'logout',
	'recover'
]
User = get_user_model()

class LoginView(View):
	""" This view handles user session creation. When a user is sent to this view, the user is prompted to provide login
		credentials. These credentials are validated and matched to a user account, hence authenticating him/her. When
		the user is authenticated, the user is logged in to the site and redirected to the last page he/she visited or
		the home page if no page was previously visited.
	"""

	def get(self, request):

		# Get redirect URL
		redirect_url = request.REQUEST.get('next', reverse_lazy('index'))

		# Check if user has been authenticated before - if so, redirect him/her to the main site
		if request.user is not None and request.user.is_authenticated():

			ActionLog.objects.log_account('User redirected since already logged in', user = request.user, status = 302)
			return redirect(redirect_url)

		# Create the login form and render the template
		form = LoginForm()
		return render_to_response('accounts/login.html', context = RequestContext(request, locals()))
	@method_decorator(csrf_protect)
	def post(self, request):

		# Get redirect URL
		redirect_url = request.REQUEST.get('next', reverse_lazy('index'))

		# Check if user has been authenticated before - if so, redirect him/her to the main site
		if request.user is not None and request.user.is_authenticated():

			ActionLog.objects.log_account('User redirected since already logged in', user = request.user, status = 302)
			return redirect(redirect_url)

		form = LoginForm(request.POST)
		if form.is_valid():

			# Login the authenticated user to the site and redirect - remember to log this event
			user = form.user
			ActionLog.objects.log_account('User logged in to site (current permissions: %s)' % user.groups, user = user, status = 200)
			login_to_site(request, user)
			update_last_login(None, user = user)

			return redirect(redirect_url)

		# Login failed - report errors back to the user
		ActionLog.objects.log_account('Failed attempt to log in to site (requested account: %s)' % form.cleaned_data['email_address'], status = 401)

		return render_to_response('accounts/login.html',
			context = RequestContext(request, locals()),
			status = 401
		)

login = LoginView.as_view()

class LogoutView(View):
	""" View that handles the user session invalidation logic. When a user is pointed to this view, the session is logged,
		invalidated and the user is redirected to the login page to sign up again (this is the default behavior).
	"""

	@method_decorator(login_required)
	def get(self, request):

		# User is logging out - log this event
		user = request.user
		ActionLog.objects.log_account('User logged out from site', user = user)

		# Proceed to log out the user
		logout_from_site(request)
		return redirect(reverse_lazy('accounts:login'))

logout = LogoutView.as_view()

class RecoverView(View):
	""" View that handles user account recovery. Recovery is carried on in two phases, each using two steps. These phases
		are "recovery" and "reset". In "recovery" phase, the account is located by means of user input and an email address
		is sent to the account to retake the process in a later time. The "reset" phase allows the user to change the
		account's password. The email sent by recovery has an expiry date of a week since the emission date and is a one-time
		only token to change the password: once used, the link is invalidated.

		This view allows changing the password of a logged-out user only. If the user was already logged in, the attempt
		is blocked since this could imply an attack. Also, the generated token is protected against tampering to prevent
		faking the request and hijacking user sessions. Once a password is changed, all active sessions (if any) are invalidated
		and the user is redirected to login.
	"""

	def get(self, request, user_id = '', token = '', stage = ''):

		# Check if user has been authenticated before - if so, redirect him/her to the main site
		if request.user is not None and request.user.is_authenticated():

			ActionLog.objects.log_account('User redirected since already logged in', user = request.user, status = 302)
			return redirect(reverse_lazy('index'))

		# This view is based on recovery stage. There are two stages: "recover" and "reset".
			# In "recover", the user account is identified and a next steps mail is sent to the user's email address
			# In "reset", the user is prompted to set a new password
		# The GET method processes both stages' form rendering. Care is taken to make this as legible as possible, and
		# as commented as possible
		if stage == 'recover':

			# We are in "recover" stage: we must ask the user for the account he/she wishes to recover
			# Add the recovery form, in "recover" mode, and render the stuff
			form = RecoveryForm(stage = stage)
			return render_to_response('accounts/recover.html', context = RequestContext(request, locals()))

		elif stage == 'reset':

			# We are in "reset" stage: we must validate the token and, if valid, prompt the user to reset his/her password
			# Identify the user - if the user is invalid, we may have an in-progress security breach
			try: user = User.objects.get(id = int(force_text(base64_decode(user_id))))
			except User.DoesNotExist: user = None

			if user is None or not tokens.check_token(user, token):

				# The URL has been tampered with - abort right now
				ActionLog.objects.log_account('URL tampering attempt detected: aborting recovery process', status = 403, user = user)
				return HttpResponseForbidden()

			form = RecoveryForm(stage = stage, user = user)
			return render_to_response('accounts/reset.html', context = RequestContext(request, locals()))

		return HttpResponseForbidden()
	@method_decorator(csrf_protect)
	def post(self, request, user_id = '', token = '', stage = ''):

		# Check if user has been authenticated before - if so, redirect him/her to the main site
		if request.user is not None and request.user.is_authenticated():

			ActionLog.objects.log_account('User redirected since already logged in', user = request.user, status = 302)
			return redirect(reverse_lazy('index'))

		if stage == 'recover':

			# Create the form in "recover" mode and attempt to validate it
			form = RecoveryForm(request.POST, stage = stage)
			if form.is_valid():

				# The form was submitted correctly, thus we send the email and notify the user on further steps
				user = form.user
				ActionLog.objects.log_account('Initiated account recovery for user (current permissions: %s)' % user.groups, user = user, status = 200)
				form.send_recovery_email(request, user, tokens.make_token(user))

				return render_to_response('accounts/recovering.html', context = RequestContext(request, locals()))

			# The account is invalid: notify this error to the user and log it
			email = form.cleaned_data['email_address']
			ActionLog.objects.log_account('Attempted to recover password of invalid account (email address: %s)' % email, status = 401)

			return render_to_response('accounts/recover.html',
				context = RequestContext(request, locals()),
				status = 401
			)
		elif stage == 'reset':

			# Identify the user - if the user is invalid, we may have an in-progress security breach
			try: user = User.objects.get(id = int(force_text(base64_decode(user_id))))
			except User.DoesNotExist: user = None

			if user is None or not tokens.check_token(user, token):

				# The URL has been tampered with - abort right now
				ActionLog.objects.log_account('URL tampering attempt detected: aborting recovery process', status = 403, user = user)
				return HttpResponseForbidden()

			# Validate the user data using the form in "complete" mode
			form = RecoveryForm(request.POST, stage = stage, user = user)
			if form.is_valid():

				# Reset the user password
				ActionLog.objects.log_account('Resetting password for user account', status = 200, user = user)
				password = form.cleaned_data['password']
				user.set_password(password)
				user.save()

				# Invalidate all sessions since they are no longer valid
				update_session(request, user)
				return redirect(reverse_lazy('accounts:login'), context = RequestContext(request, locals()))

			# The form could not be validated due to incompatible passwords
			ActionLog.objects.log_account('Attempted to change password for user', status = 401, user = user)
			return render_to_response('accounts/reset.html',
				context = RequestContext(request, locals()),
				status = 401
			)

		return HttpResponseForbidden()

recover = RecoverView.as_view()

apps/fmfn/views/createMaterial.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import redirect, render_to_response, RequestContext
from django.contrib.auth import login as login_to_site
from django.views.decorators.csrf import csrf_protect
from django.utils.decorators import method_decorator
from django.core.urlresolvers import reverse_lazy
from django.views.generic import View
from apps.fmfn.forms import materials

__all__ = [ 'createMaterial' ]


class CreateMaterialView(View):

	def post(self,request):

		# Validate the form
		form = materials(request.POST)
		if form.is_valid():

			# Log in the user into the system
			title = form.title
			description = form.description

			# Redirect the user to the main site
			return redirect(reverse_lazy('home'))

		return render_to_response('accounts/login.html', context = RequestContext(request, locals()), status = 401)
login = CreateMaterialView.as_view()

apps/fmfn/templates/users/create.html
{% extends 'base/base-2cols.html' %}
{% load i18n widget_tweaks %}

{% block usuarios-active %}
    active
{% endblock %}

{% block canvas %}
    <div class="ninenty">
        <div class="heading">
            {% trans 'Nueva cuenta de usuario' %}
        </div>

        {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
                <div class="alert-box alert">{{ error }}</div>
            {% endfor %}
        {% endif %}

        <form action="{% url 'users:create' %}" method="post" enctype="multipart/form-data" class="form">
            {% csrf_token %}
            <!-- General info section -->
            <div id="general">
                <div class="sub-heading">{% trans 'Información general' %}</div>
                <div id="user-first-name"
                     class="three-elements">{{ form.first_name | add_class:'error' | attr:'required' }}</div>
                <div id="user-father-family-name"
                     class="three-elements">{{ form.father_family_name | add_class:'error' }}</div>
                <div id="user-mother-family-name"
                     class="three-elements">{{ form.mother_family_name | add_class:'error' }}</div>
                <!-- General info section -->

                <!--Password section-->
                <div class="sub-heading">{% trans 'Contraseña' %}</div>
                <div id="user-password">
                    {{ form.password | add_class:'error element-in-block' | attr:'required' }}
                    {{ form.repeat | add_class:'error element-in-block' | attr:'required' }}
                </div>
                <!--Password section-->

                <!--User-mail section-->
                <div class="sub-heading">{% trans 'Correo electrónico' %}</div>
                <div id="user-email" class="none">
                    {{ form.email_address.errors }}{{ form.email_address | add_class:'error element-in-block' | attr:'required' }}
                </div>
                <!--User-mail section-->

                <!--Campus section-->
                <div class="sub-heading">{% trans 'Seleccione el campus del usuario' %}</div>
                <div id="user-campus">
                    {{ form.campus.errors }}
                    {{ form.campus | add_class:'error element-in-block' | attr:'required' }}
                </div>
                <!--Campus section-->

                <!--Rol section-->
                <div class="sub-heading">{% trans 'Seleccione el rol del usuario ' %}</div>
                <div id="user-roles">
                    <div id="id_role">
                        {% if form.role.errors %}
                            {% for error in form.role.errors %}
                                <div class="alert-box alert">{{ error }}</div>
                            {% endfor %}
                        {% endif %}
                        {% for role in form.fields.role.choices %}
                            <input type="radio" id="id_role_{{ forloop.counter }}" name="role"
                                   value="{{ role.0 }}" style="visibility: hidden;"/>
                            <label for="id_role_{{ forloop.counter }}" class="checkbox">
                                {% autoescape off %}{{ role.1 }}{% endautoescape %}
                            </label>
                        {% endfor %}
                    </div>
                </div>
                <!--Rol section-->
            </div>

            <!-- Teaching grades section-->
            <div class="sub-heading">{% trans 'Seleccione los grados que imparte' %}</div>
            <div id="user-grades">
                <div id="id_grades">
                    {% if form.grades.errors %}
                        {% for error in form.grades.errors %}
                            <div class="alert-box alert">{{ error }}</div>
                        {% endfor %}
                    {% endif %}
                    {% for grade in form.fields.grades.choices %}

                        <input type="checkbox" id="id_grades_{{ forloop.counter }}" name="grades"
                               value="{{ grade.0 }}" style="visibility: hidden;"/>
                        <label for="id_grades_{{ forloop.counter }}" class="checkbox">
                            {% blocktrans with grade.1|title as name %}
                                {{ name }}
                            {% endblocktrans %}
                        </label>

                    {% endfor %}

                </div>
            </div>
            <!-- Teaching grades section -->

            <!-- User picture section -->
            <div class="sub-heading">{% trans 'Seleccione la foto del usuario' %}</div>
            <div id="user-profile-photo" class="col-xs-12 form-group">
                {% if form.photo.errors %}
                    {% for error in form.photo.errors %}
                        <div class="alert-box alert">{{ error }}</div>
                    {% endfor %}
                {% endif %}
                {{ form.photo | add_class:'error' }}
            </div>
            <!-- User picture section -->


            <button class="btn btn-primary" type="submit"
                    style="margin-top: 30px;">{% trans 'Crear nuevo usuario' %}</button>
        </form>
    </div>
{% endblock %}

apps/fmfn/templates/users/edit.html
{% extends 'base/base-2cols.html' %}
{% load i18n widget_tweaks static %}
{% load roles %}

{% block title %}{% trans 'Editar usuario' %}{% endblock title %}

{% block canvas %}
    <div class="ninenty">
        <div class="heading">{% trans 'Editar usuario' %}</div>
        <div class="description">
            {% blocktrans with u.email_address as email %}Estás editando la cuenta:
                <strong>{{ email }}</strong>{% endblocktrans %}
        </div>

        <!--Errors section-->
        {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
                <div class="alert-box alert">{{ error }}</div>
            {% endfor %}
        {% endif %}
        <!--Errors section-->

        <form action="{% url 'users:edit' user_id %}" enctype="multipart/form-data" method="post" class="form">
            {% csrf_token %}

            <div id="basic" class="container-fluid">
                <div class="sub-heading">{% trans 'Public Profile' %}</div>


                <div id="user-photo" class="two-elements">
                    <div class="description emphasis">{% trans 'Foto de perfil' %}</div>
                    {{ form.photo | add_class:'form-control' }}
                </div>
                <div id="user-password" class="two-elements-exact">
                    <div class="description emphasis">{% trans 'Contraseña' %}</div>
                    {{ form.password }}<br/>
                    {{ form.repeat }}
                </div>
            </div>

            {% if form.is_managed %}
                <div id="advanced">

                    <div class="sub-heading">{% trans 'Información avanzada' %}</div>

                    <!-- General info section -->
                    <div class="description emphasis">{% trans 'Información General' %}</div>
                    <div id="user-name">
                        <div id="user-first-name"
                             class="three-elements">{{ form.first_name | add_class:'error' | attr:'required' }}</div>
                        <div id="user-father-family-name"
                             class="three-elements">{{ form.father_family_name | add_class:'error' }}</div>
                        <div id="user-mother-family-name"
                             class="three-elements">{{ form.mother_family_name | add_class:'error' }}</div>
                    </div>
                    <div class="description emphasis">{% trans 'Correo electrónico' %}</div>
                    <div id="user-email" class="element-in-block">
                        {{ form.email_address | add_class:'form-control' }}
                    </div>
                    <!-- General info section -->

                    <!--Campus section-->
                    <div class="description emphasis">{% trans 'Campus en el que imparte:' %}</div>
                    {{ form.campus | add_class:'form-control' | add_class:'element-in-block' }}
                    <!--Campus section-->

                    <!--Rol section-->
                    {% if user|has_role:'administrator' %}<div class="description emphasis">{% trans 'Rol del usuario' %}</div>
                    <div id="id_role">
                        {% for role in form.fields.role.choices %}
                            <input type="radio" id="id_role_{{ forloop.counter }}" name="role"
                                   value="{{ role.0 }}"
                                    {% if role.0 == form.role.value %} checked{% endif %}
                                   style="visibility:hidden;"/>
                            <label for="id_role_{{ forloop.counter }}" class="checkbox">
                                {% blocktrans with role.1|title as name %}{{ name }}{% endblocktrans %}
                            </label>
                        {% endfor %}
                    </div>
                    {% endif %}
                    <!--Rol section-->

                    <!-- Teaching grades section-->
                    <div class="description emphasis">{% trans 'Grados que imparte' %}</div>
                    <div id="user-grades">
                        <div id="id_grades">
                            {% for grade in form.fields.grades.choices %}
                                <input type="checkbox" id="id_grades_{{ forloop.counter }}" name="grades"
                                       value="{{ grade.0 }}"{% if grade.0 in form.grades.value %}
                                       checked{% endif %}
                                       style="visibility: hidden;"/>
                                <label for="id_grades_{{ forloop.counter }}" class="checkbox">
                                    {% blocktrans with grade.1|title as name %}{{ name }}{% endblocktrans %}
                                </label>
                            {% endfor %}
                        </div>
                    </div>
                    <!-- Teaching grades section-->

                </div>
            {% endif %}
            <button class="btn btn-primary" type="submit">{% trans 'Guardar' %}</button>

        </form>
        {% if user|has_role:'administrator' %}
        {% elif user|has_role:'content manager' %}
        {% elif user|has_role:'user manager' %}
            {% if user.id != u.id %}
                <div class="form">
                    <button class="delete-user-button" id="remove-user">{% trans 'Borrar usuario' %}</button>
                </div>
            {% endif %}
        {% endif %}
    </div>
{% endblock canvas %}
{% block js_footer %}
    <script src="{% static 'js/users.js' %}"></script>
{% endblock js_footer %}
{% block modals %}
    {% include "modals/user-edit.html" %}
{% endblock modals %}

apps/fmfn/templates/users/list.html
{% extends 'base/base-2cols.html' %}
{% load static i18n %}
{% load roles %}
{% block usuarios-active %}active{% endblock usuarios-active %}
{% block title %}{% trans 'Usuarios' %}{% endblock title %}
{% block canvas %}
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.9/css/dataTables.foundation.min.css">
    <div class="ninenty">
        {% if user|has_role:'user manager' and user.role.name != 'content manager' %}
            <hr>
            <a href="{% url 'users:create' %}" class="anchor-to-button">{% trans 'Crear nuevo usuario' %}</a>
            <hr>
            <div class="sub-heading">{% trans 'Lista de usuarios' %}</div>

            <table class="display" id="users-table" cellspacing="0" width="100%">
                <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Apellido Paterno</th>
                    <th>Apellido Materno</th>
                    <th>Email</th>
                    <th>Campus</th>
                    <th>Rol</th>
                    <th>Perfil</th>
                    <th>Editar</th>
                </tr>
                </thead>
                <tbody>
                {% for u in users %}
                    <tr>
                        <td>{{ u.first_name }} </td>
                        <td>{{ u.father_family_name }} </td>
                        <td>{{ u.mother_family_name }} </td>
                        <td>{{ u.email_address }} </td>
                        <td>{{ u.campus }} </td>
                        <td>{{ u.role }}</td>
                        <td style="text-align: center"><a href="{% url 'users:view' u.id %}"><i
                                class="fa fa-eye"></i></a></td>
                        <td style="text-align: center"><a href="{% url 'users:edit' u.id %}"><i
                                class="fa fa-pencil"></i></a></td>
                    </tr>

                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <div class="heading">{% trans 'Vista solo disponible para administrador de usuarios' %}</div>
        {% endif %}
    </div>
{% endblock canvas %}

{% block js_footer %}
    <script src="{% static 'js/list-user.js' %}"></script>
{% endblock js_footer %}